# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 47a210a6cda401596eee50629bac910c56e0cd68fd95120ef60966ce41ee47269c097b6a6cd3024bbba1370aa950f84b4d975e404b85d03f6b3629601345bb40

test:
  secret_key_base: f54c32647eb4e16bc59bc05aae1b8e02d2ea969b3ad94721611e1baf02df9d721a8c697b267c77d74f98c70e8d4d15ed7ed86801205122cdafd75002c8e2cb36

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
